server:
  port: 9090

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: false
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS

      routes:
        - id: user
          uri: lb://user
          predicates: Path=/api/user/**

        - id: auth
          uri: lb://auth
          predicates:
          - Path=/api/realm/**, /api/auth/**

        - id: backoffice
          uri: lb://backoffice
          predicates:
          - Path=/api/inventory/**, /api/item/**

auth-detail:
  uri: http://user/api/user/auth-detail/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9110/eureka

feign:
  circuitbreaker:
    enabled: true



