server:
  port: 8080

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8110/eureka

feign:
  circuitbreaker:
    enabled: true



