server:
  port: 9120

spring:
  profiles:
    active: dev  #it will not be pushed to git because it contains password

  application:
    name: auth

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9110/eureka

feign:
  circuitbreaker:
    enabled: true
  retry:
    max: 1
    interval: 2000

resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 60s

keycloak:
  realm: master
  auth-server-url: http://localhost:8071
  ssl-required: external
  resource: admin-cli
  bearer-only: true
  cors: true
  public-client: true
  connection-pool-size: 10

kc:
  admin:
    user: admin
    password: admin
  inventory-client: inventory
  client-secret: 5XsCQbsMW1RyQeMl7g250F8I8c5aY6MV